server:
  port: 8085

spring:
  config:
    import:
      - classpath:application-retry.yml
      - classpath:application-circuit-break.yml
      - classpath:application-rate-limiter.yml
      - classpath:application-bulkhead.yml
      - classpath:application-time-limiter.yml
      - classpath:application-payment-example.yml

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,retries
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

logging:
  level:
    io.github.resilience4j.bulkhead: TRACE
    com.malbano.resilience4j.samples: DEBUG
    io.github.resilience4j: DEBUG

client.api:
  url-base: http://localhost:8085
  path-products: /internal-api/products
  path-payment: /internal-api/payment
  path-database: /internal-api/database/reports

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  show-actuator: true


