resilience4j:
  ratelimiter:
    configs:
      default-per-user:
        limit-for-period: 5
        limit-refresh-period: 15s
        timeout-duration: 0s
        register-health-indicator: false

    instances:
      basic-rate-limiter:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 0s

      rate-limiter-with-wait:
        limit-for-period: 3
        limit-refresh-period: 10s
        timeout-duration: 5s
