resilience4j:
  timelimiter:
    instances:
      api-product-stoppable:
        timeout-duration: 2s
        cancel-running-future: true

      api-product-unstoppable:
        timeout-duration: 2s
        cancel-running-future: false

